name: Build

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.0'
    - name: Test and clean
      run: |
        make test
        make clean
    - name: Cross build CLI
      run: make cross
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          gocerts-linux-amd64
          gocerts-windows-amd64.exe
          gocerts-darwin-amd64          

